// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package aarm

import (
	"github.com/aws/aws-sdk-go-v2/aws"
)

// Injectors from wire.go:

func NewApp(cfg aws.Config) *App {
	client := newAppRunner(cfg)
	aarmAppRunner := &appRunner{
		DeploymentStarter: client,
		ServiceDescriber:  client,
		ServicesLister:    client,
	}
	app := newApp(aarmAppRunner)
	return app
}
