// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package aarm

import (
	"context"
)

// Injectors from wire.go:

func NewApp(ctx context.Context, opts *GlobalOptions) (*App, error) {
	config, err := newAWSConfig(ctx, opts)
	if err != nil {
		return nil, err
	}
	client := newAppRunner(config)
	aarmAppRunner := &appRunner{
		DeploymentStarter: client,
		ServiceCreator:    client,
		ServiceDescriber:  client,
		ServicesLister:    client,
		ServiceUpdater:    client,
	}
	app, err := newApp(aarmAppRunner, opts)
	if err != nil {
		return nil, err
	}
	return app, nil
}
